### ISSUE TITLE
Leaking reference

### ISSUE THREAD

**Issue by morriq** [ng-hal/ng-hal#49]
Hello,
There is leaking reference. Please take a look on it :)

```
let link = resource.link('comments');
link.href += 'https://google.com' + link.href; // https://google.com/comments

link2 = resource.link('comments');
link2.href = 'https://google.com' + link2.href; // https://google.comhttps://google.com/comments
```

**Comment by dherges** [comment]
@morriq thanks for reporting!

If I was using `ng-hal` in production code, I'd use it in conjunction with immutable objects, e.g. [Immutable Records](https://facebook.github.io/immutable-js/docs/#/) - which requires that you add another "thin" layer on top of the `Navigator` API...
