### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by ctaepper** [ng-hal/ng-hal#90]
Hi, you are doing a lot of work on this lib right now. do you have any plans for a next release? I am starting to use this lib, however, i have concerns about getting into it while you do some heavy refactoring and come up with breaking changes. So a little heads up would be great :)

**Comment by dherges** [comment]
Hi,

good questions.

Do I have plans for a next release?

No.

In general, what is the status of this GitHub repo?

It's a side project. Open topics:
- migrating to HttpClient for angular 5 and beyond
- implementing the DSL for resource traversing and resource building
- fixing the build errors (as of now)
- testing of the library
- improve demo application w/ real world API mock data 

We do not actively use HAL APIs at my employer. I explore some HAL APIs in one (1!!) new project at work and one private side experiment. I do not know when a release will come next. The DSL linksFrom, embeddedFrom feels good from the limited experience of the small projects. I'd like to stick with it.

If you intend to use on production, you can use one of the versions published at npm. Do not expect any new features or big fixes there.

If a new release would come, it will be a major version increase. Definetely braking changes to the current versions.

If you like to use the newer things and want the open topics, I'd be willing to Crete a GitHub organisation and put the repo into ownership of the org. I'd be happy to add you (and other people actively wanting and using the lib) to the organisation.



Cheers, David

**Comment by dherges** [comment]
Let me ask: are you interested in contributing / maintaining to ng-hal if it was owned by a GitHub / npm org?

**Comment by izub** [comment]
Hi @dherges , any chance we could get a tiny release which will add support for Angular 5?
Currently ng-hal is the only package which blocks us from upgrading. This release would only fix the breaking changes by 5.0 in ng-hal.

**Comment by izub** [comment]
As for your question about a github/npm org, I can't make any promises myself but I think it would definitely help with getting more people to contribute to the project.

**Comment by tiagofe** [comment]
Hi dherges. How can I contribute to ng-hal? In the moment we are using this library and we need correct some issues. Thanks!

**Comment by drewfreyling** [comment]
@tiagofe I can see the source? E.G: https://github.com/dherges/ng-hal/blob/master/packages/http/src/transport/hal-interceptor.ts

**Comment by robert-ovens** [comment]
Hi @dherges ,

If you are ok with creating a GitHub org for this library, then I've got a bunch of engineers ready to make contributions. We've got an engineering team of around 40, and HAL is a core part of our API philosophy. As we move to Angular 4+ we need this library as part of our UI service offering. 

As a priority we would;
- make the changes to support HttpClient. 
- document any CI stuff (I can see a circleci file so that's sweet)

We would also be interested in adding to an associated GitHub project site so we can have some examples to help onboard our customers in using this library if they are using Angular. If you're cool with this then please proceed to setting up the GitHub account and include myself and @drewfreyling (one of our engineering leads). 

Kind regards,
Robert.

**Comment by dherges** [comment]
Hi @robert-ovens,

that's fine to me.

Will you create a GitHub org? and I will transfer ownership of the repository to your org.

**Comment by drewfreyling** [comment]
@dherges we have created https://github.com/ng-hal

**Comment by dherges** [comment]
Here we are!

**Comment by drewfreyling** [comment]
Great. @robert-ovens @dherges lets create a roadmap/issues for what we want to achieve from above.

**Comment by drewfreyling** [comment]
@ctaepper closing as the project is alive!

**Comment by izub** [comment]
@drewfreyling @dherges any chance I could get a rough ETA on when we can expect a version offering Angular 5/6 support? I need to make a decision on whether or not we should continue using ng-hal for our projects at work.

**Comment by drewfreyling** [comment]
Assuming the changes are trivial we are hoping to get this out next month.
